name: Deploy to Azure WebApp

on:
  push:
    branches:
      - main # Cette ligne doit correspondre à la branche qui contient votre code à déployer

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'defaultworker-euw' # Remplacez ceci par le nom de votre Web App Azure
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Assurez-vous d'avoir configuré ce secret dans GitHub
        package: '.' # Ici, '.' désigne la racine du dépôt, qui est supposée contenir le contenu publié
