name: Deploy to Azure WebApp

on:
  push:
    branches:
      - main # Assurez-vous que cela correspond au nom de votre branche principale

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Assurez-vous que cela correspond à la version de votre application

    # Pas nécessaire si vous avez déjà construit et publié votre application
    # - name: Build with dotnet
    #   run: dotnet build --configuration Release

    # - name: Publish with dotnet
    #   run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'defaultworker-euw' # Remplacez par le nom de votre application Web Azure
        slot-name: 'production' # Supprimez ou modifiez cette ligne si vous n'utilisez pas de slots
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Assurez-vous d'avoir configuré cela dans vos secrets GitHub
        package: '.' # Mettez le chemin vers votre dossier publish si nécessaire
